#!/bin/bash
config="../../configs"

function kitty_i {
	if ! pacman -Qs kitty > /dev/null ; then
  		sudo pacman -S kitty
	fi
	mkdir -p ~/.config/kitty
	ln $config/kitty/kitty.conf ~/.config/kitty/kitty.conf
}
function alacritty_i {
	if ! pacman -Qs alacritty > /dev/null ; then
  		sudo pacman -S alacritty
	fi
	mkdir -p ~/.config/alacritty
	ln $config/alacritty/alacritty.yml ~/.config/alacritty.yml
}
function st_i {
	cd ~/software
	git clone https://git.suckless.org/st
	cd st
	sudo make clean install
}
function gnome_i {
	if ! pacman -Qs gnome-terminal > /dev/null ; then
  		sudo pacman -S gnome-terminal
	fi
}
function konsole_i {
	if ! pacman -Qs konsole > /dev/null ; then
  		sudo pacman -S konsole
	fi
}
function unknown_i {
	if ! pacman -Qs $1 > /dev/null ; then
  		sudo pacman -S $1
	fi
}
case "$1" in 
	kitty ) 	kitty_i ;;
	alacritty ) 	alacritty_i ;;
	st ) 		st_i ;;
	konsole ) 	konsole_i ;;
	(*) ) 		unknown_i ;;
esac
