#! /bin/sh

sxhkd &
tint2 > \dev\null&
background &


bspc monitor $mon1 -d Term Web Fill
bspc monitor $mon2 -d Doc Music Commun
bspc config window_gap		20
bspc config border_width         2
bspc config left_padding			 33
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
